markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
permalink: /404.md
excerpt_separator: ""

gauges_id: 
google_analytics_id: 
google_site_verification: 

repository: 
help_url: 

timezone: America/Los_Angeles

name: Skills • Skills Now
description: Transform your learning into skills
url: http://skills.ml

twitter:
  username: skills_ml

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
